version: 1

parameters:
  domain:
    legal:
      - parcel
      - vehicle
  company:
    legal:
      - rmg
      - sainsbury
      - oneVanMan
  product:
    - firstClass
    - secondClass
    - signedForFirstClass
    - signedForSecondClass
    - tracked24
    - tracked48
  event:
    - created
    - collected
    - arrived
    - departed
    - outForDelivery
    - signedFor
    - delivered


files:
  - notifications.yaml  # This is the file that contains the tasks for notifications
  - tasks.yaml  # This is the file that contains the tasks that are needed by the system
  - services.yaml  # This is the file that contains services that implement the tasks
  - modules.yaml  # This is the file that contains the modules that are used by the system
  - company/{domain}_{company}.yaml  # This is the file that contains the company specific configuration
  - company/{domain}_{company}/{event}.yaml  # This is the file that contains the company and event specific configuration
  - product/{domain}_{product}.yaml  # This is the file that contains the product specific configuration
  - product/{domain}_{product}/{event}.yaml  # This is the file that contains the product and event specific configuration
  - company/product/{company}/{domain}_{company}_{product}.yaml  # This is the file that contains the company and product specific configuration
  - company/product/{company}/{product}/{domain}_{company}_{event}.yaml  # This is the file that contains the company, product and event specific configuration
